//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_ENGLISH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauHoi()
        {
            this.DapAns = new HashSet<DapAn>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaDeThi { get; set; }
        public string CauHoi1 { get; set; }
        public string Dap_an_a { get; set; }
        public string Dap_an_b { get; set; }
        public string Dap_an_c { get; set; }
        public string Dap_an_d { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DeThi DeThi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DapAn> DapAns { get; set; }
    }
}
