//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_ENGLISH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DapAn
    {
        public int Id { get; set; }
        public Nullable<int> MaCauHoi { get; set; }
        public string Dap_an_A { get; set; }
        public string Dap_an_B { get; set; }
        public string Dap_an_C { get; set; }
        public string Dap_an_D { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
    }
}
