//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_ENGLISH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> category_id { get; set; }
        public string avatar { get; set; }
        public string origin { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public string detail { get; set; }
        public Nullable<int> sale { get; set; }
    }
}
